apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: import-disk
  namespace: beehive-virtual-machines
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi